
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ACER
 */
public class KonversiSuhuFrame extends javax.swing.JFrame {

    void hitungSuhu() {
        try {
            double inputSuhu = Double.parseDouble(inputTextField.getText());
            String skalaAwal = (String) skalaAwalComboBox.getSelectedItem();
            double hasil = 0;
            String skalaTujuan;

            if (rbtnCelcius.isSelected()) {
                skalaTujuan = "Celcius";
            } else if (rbtnReamur.isSelected()) {
                skalaTujuan = "Reamur";
            } else if (rbtnKelvin.isSelected()) {
                skalaTujuan = "Kelvin";
            } else if (rbtnFahrenheit.isSelected()) {
                skalaTujuan = "Fahrenheit";
            } else {
                JOptionPane.showMessageDialog(this, "Skala Akhir belum dipilih!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if ("Celcius".equals(skalaAwal) && "Fahrenheit".equals(skalaTujuan)) {
                hasil = (inputSuhu * 9 / 5) + 32;
            } else if ("Celcius".equals(skalaAwal) && "Kelvin".equals(skalaTujuan)) {
                hasil = inputSuhu + 273.15;
            } else if ("Celcius".equals(skalaAwal) && "Reamur".equals(skalaTujuan)) {
                hasil = inputSuhu * 4 / 5;
            } else if ("Fahrenheit".equals(skalaAwal) && "Celcius".equals(skalaTujuan)) {
                hasil = (inputSuhu - 32) * 5 / 9;
            } else if ("Fahrenheit".equals(skalaAwal) && "Kelvin".equals(skalaTujuan)) {
                hasil = (inputSuhu - 32) * 5 / 9 + 273.15;
            } else if ("Fahrenheit".equals(skalaAwal) && "Reamur".equals(skalaTujuan)) {
                hasil = (inputSuhu - 32) * 4 / 9;
            } else if ("Kelvin".equals(skalaAwal) && "Celcius".equals(skalaTujuan)) {
                hasil = inputSuhu - 273.15;
            } else if ("Kelvin".equals(skalaAwal) && "Fahrenheit".equals(skalaTujuan)) {
                hasil = (inputSuhu - 273.15) * 9 / 5 + 32;
            } else if ("Kelvin".equals(skalaAwal) && "Reamur".equals(skalaTujuan)) {
                hasil = (inputSuhu - 273.15) * 4 / 5;
            } else if ("Reamur".equals(skalaAwal) && "Celcius".equals(skalaTujuan)) {
                hasil = inputSuhu * 5 / 4;
            } else if ("Reamur".equals(skalaAwal) && "Fahrenheit".equals(skalaTujuan)) {
                hasil = (inputSuhu * 9 / 4) + 32;
            } else if ("Reamur".equals(skalaAwal) && "Kelvin".equals(skalaTujuan)) {
                hasil = (inputSuhu * 5 / 4) + 273.15;
            } else {
                hasil = inputSuhu; // Jika skala awal dan tujuan sama
            }
            // Tambahkan rumus konversi lain sesuai skala yang dipilih

            hasilLabel.setText("Hasil: " + hasil + " " + skalaTujuan);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Creates new form KonversiSuhuFrame
     */
    public KonversiSuhuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        inputTextField = new javax.swing.JTextField();
        skalaAwalComboBox = new javax.swing.JComboBox<>();
        konversiButton = new javax.swing.JButton();
        hasilLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbtnFahrenheit = new javax.swing.JRadioButton();
        rbtnKelvin = new javax.swing.JRadioButton();
        rbtnReamur = new javax.swing.JRadioButton();
        rbtnCelcius = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                inputTextFieldCaretUpdate(evt);
            }
        });
        inputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputTextFieldKeyTyped(evt);
            }
        });

        skalaAwalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Fahrenheit", "Reamur", "Kelvin", " " }));

        konversiButton.setText("Konversi");
        konversiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konversiButtonActionPerformed(evt);
            }
        });

        hasilLabel.setText("Konversi Suhu");

        jLabel1.setText("Konversi ke");

        buttonGroup1.add(rbtnFahrenheit);
        rbtnFahrenheit.setSelected(true);
        rbtnFahrenheit.setText("Fahrenheit");
        rbtnFahrenheit.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnFahrenheitItemStateChanged(evt);
            }
        });
        rbtnFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFahrenheitActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnKelvin);
        rbtnKelvin.setText("Kelvin");
        rbtnKelvin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnKelvinItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbtnReamur);
        rbtnReamur.setText("Reamur");
        rbtnReamur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnReamurItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbtnCelcius);
        rbtnCelcius.setText("Celcius");
        rbtnCelcius.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnCelciusItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hasilLabel)
                        .addGap(29, 29, 29)
                        .addComponent(konversiButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(skalaAwalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))
                            .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnFahrenheit)
                            .addComponent(rbtnReamur))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnCelcius)
                            .addComponent(rbtnKelvin))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skalaAwalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(rbtnFahrenheit)
                    .addComponent(rbtnKelvin))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnReamur)
                    .addComponent(rbtnCelcius))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konversiButton)
                    .addComponent(hasilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void konversiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konversiButtonActionPerformed
        hitungSuhu();       // TODO add your handling code here:
    }//GEN-LAST:event_konversiButtonActionPerformed

    private void inputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.') {
            evt.consume(); // Membatasi input hanya untuk angka dan titik desimal
        }        // TODO add your handling code here:
    }//GEN-LAST:event_inputTextFieldKeyTyped

    private void rbtnFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFahrenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFahrenheitActionPerformed

    private void rbtnFahrenheitItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnFahrenheitItemStateChanged
        if (rbtnFahrenheit.isSelected())
            hitungSuhu();        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFahrenheitItemStateChanged

    private void rbtnReamurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnReamurItemStateChanged
       if (rbtnReamur.isSelected())
            hitungSuhu();      // TODO add your handling code here:
    }//GEN-LAST:event_rbtnReamurItemStateChanged

    private void rbtnKelvinItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnKelvinItemStateChanged
        if (rbtnKelvin.isSelected())
            hitungSuhu();          // TODO add your handling code here:
    }//GEN-LAST:event_rbtnKelvinItemStateChanged

    private void rbtnCelciusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnCelciusItemStateChanged
        if (rbtnCelcius.isSelected())
            hitungSuhu();  
    }//GEN-LAST:event_rbtnCelciusItemStateChanged

    private void inputTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_inputTextFieldCaretUpdate
       if (inputTextField.getText().isEmpty()== false)
           hitungSuhu();
    }//GEN-LAST:event_inputTextFieldCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel hasilLabel;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton konversiButton;
    private javax.swing.JRadioButton rbtnCelcius;
    private javax.swing.JRadioButton rbtnFahrenheit;
    private javax.swing.JRadioButton rbtnKelvin;
    private javax.swing.JRadioButton rbtnReamur;
    private javax.swing.JComboBox<String> skalaAwalComboBox;
    // End of variables declaration//GEN-END:variables
}
